version: '3.6'
services:
  # elasticsearch
  elasticsearch:
    build: .
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./es_data/:/usr/share/elasticsearch/data/
    environment:
      - ELASTIC_PASSWORD=elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
      - cluster.name=docker-cluster
    networks:
      - elasticsearch_network
  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601"
#    volumes:
#      - ./kibanaconf/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elasticsearch_network

networks:
  elasticsearch_network:
    external: true
